"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-07-10 15:01:20.223446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_initial_schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.Enum('PANEL_USER', 'SYSTEM', 'BOT', name='auditactortypeenum', native_enum=False), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('giveaways',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('ticket_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_issued', sa.Integer(), nullable=False),
    sa.Column('is_registration_open', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('digital_poster_file_id', sa.String(length=512), nullable=True),
    sa.Column('digital_poster_caption', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('panel_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMINISTRATOR', 'OPERATOR', name='panelroleenum', native_enum=False), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_users_login'), 'panel_users', ['login'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=True),
    sa.Column('vk_username', sa.String(length=64), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_phone'), 'participants', ['phone'], unique=True)
    op.create_index(op.f('ix_participants_telegram_user_id'), 'participants', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_participants_vk_user_id'), 'participants', ['vk_user_id'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_provider_override', sa.Enum('TBANK', 'VTB', name='paymentproviderenum', native_enum=False), nullable=True),
    sa.Column('support_contact', sa.String(length=255), nullable=True),
    sa.Column('poster_settings_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('audience_filter', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'VK', 'BOTH', name='broadcastchannelenum', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENDING', 'SENT', 'FAILED', name='broadcaststatusenum', native_enum=False), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['panel_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('giveaway_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', name='manualregistrationstatusenum', native_enum=False), nullable=False),
    sa.Column('operator_id', sa.String(length=36), nullable=False),
    sa.Column('cancelled_by_id', sa.String(length=36), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['panel_users.id'], ),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['panel_users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_registrations_giveaway_id'), 'manual_registrations', ['giveaway_id'], unique=False)
    op.create_index(op.f('ix_manual_registrations_operator_id'), 'manual_registrations', ['operator_id'], unique=False)
    op.create_index(op.f('ix_manual_registrations_participant_id'), 'manual_registrations', ['participant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('giveaway_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('TBANK', 'VTB', name='paymentproviderenum', native_enum=False), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='paymentstatusenum', native_enum=False), nullable=False),
    sa.Column('payment_url', sa.String(length=1024), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=191), nullable=True),
    sa.Column('raw_webhook_payload', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_payments_giveaway_id'), 'payments', ['giveaway_id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_payments_participant_id'), 'payments', ['participant_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('giveaway_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('full_code', sa.String(length=64), nullable=False),
    sa.Column('participant_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('ONLINE', 'MANUAL', name='ticketsourceenum', native_enum=False), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('manual_registration_id', sa.String(length=36), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.ForeignKeyConstraint(['manual_registration_id'], ['manual_registrations.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_full_code'), 'tickets', ['full_code'], unique=True)
    op.create_index(op.f('ix_tickets_giveaway_id'), 'tickets', ['giveaway_id'], unique=False)
    op.create_index(op.f('ix_tickets_manual_registration_id'), 'tickets', ['manual_registration_id'], unique=False)
    op.create_index(op.f('ix_tickets_participant_id'), 'tickets', ['participant_id'], unique=False)
    op.create_index(op.f('ix_tickets_payment_id'), 'tickets', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_payment_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_participant_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_manual_registration_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_giveaway_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_full_code'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_participant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_giveaway_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_manual_registrations_participant_id'), table_name='manual_registrations')
    op.drop_index(op.f('ix_manual_registrations_operator_id'), table_name='manual_registrations')
    op.drop_index(op.f('ix_manual_registrations_giveaway_id'), table_name='manual_registrations')
    op.drop_table('manual_registrations')
    op.drop_table('broadcasts')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_participants_vk_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_telegram_user_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_phone'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_panel_users_login'), table_name='panel_users')
    op.drop_table('panel_users')
    op.drop_table('giveaways')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
