"""sync manual_registration confirmed_at

Revision ID: 0002_manual_registration_confirmed_at
Revises: 0001_initial_schema
Create Date: 2026-07-10 15:20:06.300374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_manual_registration_confirmed_at'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_registrations', sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_registrations', 'confirmed_at')
    # ### end Alembic commands ###
